version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: "make binaries" 
  generate-proto:
    docker:
      - image: grpc/go
    steps:
      - checkout
      - run: "make generate-proto"
  test-success:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: "make test-impl cmd-parser-text=echo"
  test-fail:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: "! make test-impl cmd-parser-text=false"
